/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.SoNumeros;
import Controller.CadastroDeClientes;
import Model.Database;
import Controller.CadastroDeServico;
import Controller.GeradorDePdf;
import Controller.ProdutoTableModelConsultaOrdemDeServico;
import Controller.ProdutoTableModelOrdemDeServico;
import Model.OrdemDeServicoDAO;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Emerson
 */
public class FormOrdemDeServico extends javax.swing.JFrame {

    private Connection con;

    ProdutoTableModelOrdemDeServico tableModel = new ProdutoTableModelOrdemDeServico(); // Instancio a classe de tabelas

    ProdutoTableModelConsultaOrdemDeServico tabelaConsultaOrdem = new ProdutoTableModelConsultaOrdemDeServico();  // Instancio a classe de tabelas

    DefaultListModel MODELO;

    int Enter = 0;
    int Enter1 = 0;

    public FormOrdemDeServico() {
        initComponents();
        setResizable(false);//Não permite editar o tamanho
        this.setLocationRelativeTo(null);//Centralizar Jframe
        setIconImage(Toolkit.getDefaultToolkit().getImage("c:/SISOS/Imagem/sistema.png"));
        BuscarProdutos();
        txtPesquisaCliente.requestFocus();
        txtOs.setDocument(new SoNumeros());
        txtQuantidade.setDocument(new SoNumeros());
        txtOsConsulta.setEditable(false);
        txtClienteConsulta.setEditable(false);
        Inicializar();
        textoValor.setText("0");
        txtDesconto.setText("0");
        Lista.setVisible(false);
        listaConsultaCliente.setVisible(false);
        MODELO = new DefaultListModel();
        Lista.setModel(MODELO);
        listaConsultaCliente.setModel(MODELO);
        Data();
        BuscarOS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jtConsultaOrdens = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lista = new javax.swing.JList<>();
        comboBoxProduto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrdemDeServico = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoValor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoQuantidadeDeItens = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoComplemento = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        txtDataEHora = new javax.swing.JLabel();
        txtPesquisaCliente = new javax.swing.JTextField();
        jDataDoAgendamento = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jHorarioAgendamento = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        listaConsultaCliente = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        cmdAberto = new javax.swing.JCheckBox();
        cmdFechado = new javax.swing.JCheckBox();
        cmdTodos = new javax.swing.JCheckBox();
        cmdCancelado = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        cmdOs = new javax.swing.JCheckBox();
        cmdCliente = new javax.swing.JCheckBox();
        btnBuscar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtOsConsultaInformar = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        txtPesquisaClienteConsulta = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtOsConsulta = new javax.swing.JTextField();
        clien = new javax.swing.JLabel();
        txtClienteConsulta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboBoxStatusConsulta = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerar e Consulta Ordens de Saída");
        setLocation(new java.awt.Point(5, 40));

        jLayeredPane1.setToolTipText("Gerar e Consultar Ordens de Saída");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        jLabel1.setText("Produtos:");

        Lista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListaMousePressed(evt);
            }
        });

        jLabel2.setText("Quantidade:");

        tbOrdemDeServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produtos", "Valor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbOrdemDeServico);
        if (tbOrdemDeServico.getColumnModel().getColumnCount() > 0) {
            tbOrdemDeServico.getColumnModel().getColumn(1).setMinWidth(100);
            tbOrdemDeServico.getColumnModel().getColumn(1).setMaxWidth(100);
            tbOrdemDeServico.getColumnModel().getColumn(2).setMinWidth(80);
            tbOrdemDeServico.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseClicked(evt);
            }
        });
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel3.setText("Data do Agendamento:");

        jLabel4.setText("Valor Total:");

        textoValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setText("Total de Itens:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel6.setText("Desconto:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Comlemento"));

        jScrollPane2.setViewportView(textoComplemento);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel7.setText(" Cliente:");

        txtDataEHora.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        txtPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaClienteActionPerformed(evt);
            }
        });
        txtPesquisaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaClienteKeyReleased(evt);
            }
        });

        jLabel8.setText("OS:");

        txtOs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setText("Horario:");

        jHorarioAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHorarioAgendamentoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(textoQuantidadeDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5)
                                .addComponent(textoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDataDoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jHorarioAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addComponent(txtPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 167, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOs, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDataEHora, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(txtDataEHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(comboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAdicionar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(textoQuantidadeDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jDataDoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jHorarioAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jtConsultaOrdens.addTab("Ordem de Serviço", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaConsultaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaConsultaClienteMousePressed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Status", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        cmdAberto.setText("Aberto");
        cmdAberto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdAbertoMousePressed(evt);
            }
        });

        cmdFechado.setText("Fechado");
        cmdFechado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdFechadoMousePressed(evt);
            }
        });

        cmdTodos.setText("Todos");
        cmdTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdTodosMousePressed(evt);
            }
        });

        cmdCancelado.setText("Cancelado");
        cmdCancelado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdCanceladoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdAberto)
                    .addComponent(cmdCancelado))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdTodos)
                    .addComponent(cmdFechado))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(cmdAberto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdFechado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdCancelado)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(cmdTodos)
                        .addContainerGap())))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tipo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        cmdOs.setText("OS");
        cmdOs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdOsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdOsMousePressed(evt);
            }
        });

        cmdCliente.setText("Clientes");
        cmdCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdClienteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdOs)
                .addGap(18, 18, 18)
                .addComponent(cmdCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cmdOs)
                .addComponent(cmdCliente))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOsConsultaInformar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOsConsultaInformar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        txtPesquisaClienteConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaClienteConsultaActionPerformed(evt);
            }
        });
        txtPesquisaClienteConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaClienteConsultaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisaClienteConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisaClienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(listaConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(listaConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 800, 160));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaConsultaMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaConsulta);

        jLabel10.setText("OS:");

        txtOsConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOsConsulta.setForeground(new java.awt.Color(0, 0, 204));

        clien.setText("Cliente:");

        txtClienteConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtClienteConsulta.setForeground(new java.awt.Color(0, 0, 204));

        jLabel11.setText("Status:");

        comboBoxStatusConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboBoxStatusConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABERTO", "FECHADO", "CANCELADO" }));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvar.png"))); // NOI18N
        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf.png"))); // NOI18N
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287)
                .addComponent(btnPdf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(txtOsConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clien)
                .addGap(4, 4, 4)
                .addComponent(txtClienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxStatusConsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOsConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxStatusConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(clien)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, 800, 340));

        jtConsultaOrdens.addTab("Consulta Ordens", jPanel4);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        btnEditar.setText("Buscar");
        btnEditar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBuscar1.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        btnBuscar1.setText("Cancelar");
        btnBuscar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        btnSalvar1.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        btnSalvar1.setText("Alterar");
        btnSalvar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jtConsultaOrdens, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtConsultaOrdens))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtConsultaOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inicializar() {
        tbOrdemDeServico.setModel(tableModel);         // adiciono a tabela do Swing a classe de tabela 
        tabelaConsulta.setModel(tabelaConsultaOrdem); // adiciono a tabela do Swing a classe de tabela 
        textoValor.setForeground(Color.green);
        txtQuantidade.setText("1");
        Mascaras();
        txtPesquisaClienteConsulta.setEnabled(false);
        txtOsConsultaInformar.setEnabled(false);
    }

    private void Data() {
        Date data = new Date(System.currentTimeMillis());
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy - HH:mm");
        String dataFormatada = dateFormat.format(data);
        txtDataEHora.setText(dataFormatada);
    }

    //CRUD
    private void Conexao() {
        this.con = Database.getConnection();
    }

    private void Mascaras() {

        MaskFormatter maskDataAgendamento, maskHorarioAgendamento;

        try {

            maskDataAgendamento = new MaskFormatter("##/##/####");
            maskDataAgendamento.install(jDataDoAgendamento);

            maskHorarioAgendamento = new MaskFormatter("##:##");
            maskHorarioAgendamento.install(jHorarioAgendamento);

        } catch (ParseException ex) {
            Logger.getLogger(FormClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void Limpar() {
        txtDesconto.setText("");
        txtQuantidade.setText("1");
        jDataDoAgendamento.setText("");
        textoValor.setText("0");
        txtDesconto.setText("0");
        jHorarioAgendamento.setText("");
        textoComplemento.setText("");
        txtPesquisaCliente.setText("");
        textoQuantidadeDeItens.setText("");
        txtClienteConsulta.setText("");
        txtOsConsulta.setText("");
        txtOsConsultaInformar.setText("");
        txtPesquisaClienteConsulta.setText("");

        int contadorTabela = tableModel.getRowCount();

        for (int x = 0; x < contadorTabela; x++) {
            tableModel.removeRow(0);
        }

        int contadorTabelaConsulta = tabelaConsulta.getRowCount();

        for (int x = 0; x < contadorTabelaConsulta; x++) {
            tabelaConsultaOrdem.removeRow(0);
        }

        cmdOs.setSelected(false);
        cmdCliente.setSelected(false);
        cmdAberto.setSelected(false);
        cmdFechado.setSelected(false);
        cmdTodos.setSelected(false);
        txtOsConsultaInformar.setEnabled(false);
        txtOsConsultaInformar.setEnabled(false);

        BuscarOS();
    }

    private void ListaDePesquisa() {

        MODELO.removeAllElements();

        CadastroDeServico ser = new CadastroDeServico();
        ser.setCliente(txtPesquisaCliente.getText());

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();
        List<CadastroDeServico> lista = serDao.ListaDePesquisa(ser);

        int v = 0;
        for (int x = 0; x < lista.size(); x++) {
            MODELO.addElement(lista.get(x).getCliente());
            v++;
        }
        if (v >= 1) {
            Lista.setVisible(true);
        } else {
            Lista.setVisible(false);
        }

    }

    private void MostrarPesquisa() {

        txtPesquisaCliente.setText(Lista.getSelectedValue());

    }

    private void ListaDePesquisaConsulta() {

        MODELO.removeAllElements();

        CadastroDeServico ser = new CadastroDeServico();
        ser.setCliente(txtPesquisaClienteConsulta.getText());

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();
        List<CadastroDeServico> lista = serDao.ListaDePesquisaConsulta(ser);

        int v = 0;
        for (int x = 0; x < lista.size(); x++) {
            MODELO.addElement(lista.get(x).getCliente());
            v++;
        }
        if (v >= 1) {
            listaConsultaCliente.setVisible(true);
        } else {
            listaConsultaCliente.setVisible(false);
        }

    }

    private void MostrarPesquisaConsulta() {

        txtPesquisaClienteConsulta.setText(listaConsultaCliente.getSelectedValue());

    }

    private void BuscarProdutos() {

        CadastroDeServico ser = new CadastroDeServico();

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();

        List<String> lista = serDao.BuscarProdutos(ser);

        for (int x = 0; x < lista.size(); x++) {
            comboBoxProduto.addItem(lista.get(x));
        }

    }

    private double InsereValorNaTabela() {

        CadastroDeServico ser = new CadastroDeServico();
        ser.setDescricao((String) comboBoxProduto.getSelectedItem());

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();
        serDao.InsereValorNaTabela(ser);

        double valor = ser.getValorTotal();

        return valor;
    }

    private void ContadorDaTabela() {
        // Soma a quantidade de linhas na Tabela
        int somaLinhas = tableModel.getRowCount();
        textoQuantidadeDeItens.setText(Integer.toString(somaLinhas));

        // Conta a Coluna Valor 
        double somaTotal = 0;
        double Total = 0;
        double quantidade = 0;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            Total = Double.parseDouble(tableModel.getValueAt(i, 1).toString());
            quantidade = Double.parseDouble(tableModel.getValueAt(i, 2).toString());
            somaTotal += (Total * quantidade);
        }
        textoValor.setText("" + somaTotal);
    }

    private void InserirNaTabela() {
        CadastroDeServico p = new CadastroDeServico();

        //Pegando os Valores dos campos e jogando para a TableModal
        p.setDescricao(comboBoxProduto.getSelectedItem().toString());
        CadastroDeServico ser = new CadastroDeServico();
        p.setValorTotal(InsereValorNaTabela());
        p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));

        // Adiciono os itens na tabela pela classe da TableModal
        tableModel.addRow(p);

        ContadorDaTabela(); //Chama o metodo de Somar o Valor total e a quantidade de linhas na tabela
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        /*
            O cliente gera uma OS somente com o  problema relatado e os dados do cliente
            Depois de fazer a visita ao seu cliente ele busca a OS e adiciona os Itens na OS
         */
        VerificaCodigoNoBanco(); // verifico se ja tem algum código cadastrado no banco para fazer a alteração ou a inserção dos dados pelo botão Salvar

    }//GEN-LAST:event_btnSalvarActionPerformed

    public void VerificaCodigoNoBanco() {

        CadastroDeServico ser = new CadastroDeServico();

        ser.setOs(Integer.parseInt(txtOs.getText()));

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();

        serDao.VerificaCodigoNoBanco(ser);
        serDao.VerificaCodigoDeItensNoBanco(ser);

        if (ser.isValidadorItens()) { // se o codigo da nota existir no banco NA TABELA DE ITENS
            GerarPDF(); //Gero PDF 
        } else {
            if (ser.isValidadorNota()) {   //UPDATE
                SalvarItens(); //Salvo o Itens da Nota
                GerarPDF(); //Gero PDF 

                ser.setCliente(txtPesquisaCliente.getText());
                ser.setOs(Integer.parseInt(txtOs.getText()));
                ser.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                ser.setComplemento(textoComplemento.getText());
                ser.setDesconto(Double.parseDouble(txtDesconto.getText().replace(",", ".")));
                ser.setValorTotal(Double.parseDouble(textoValor.getText().replace(",", ".")));
                ser.setDataAgendamento(jDataDoAgendamento.getText());
                ser.setHorarioAgendamento(jHorarioAgendamento.getText());

                serDao.AlterarNota(ser);

            } else {                   //INSERT
                Salvar(); //Salvo os complementos da nota
                GerarPDF(); //Gero PDF 
            }
        }

        Limpar();

    }

    public void Salvar() {

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();
        CadastroDeServico ser = new CadastroDeServico();

        ser.setCliente(txtPesquisaCliente.getText());
        ser.setValorTotal(Double.parseDouble(textoValor.getText()));
        ser.setDesconto(Double.parseDouble(txtDesconto.getText().replace(",", ".")));
        ser.setDataAgendamento(jDataDoAgendamento.getText());
        ser.setHorarioAgendamento(jHorarioAgendamento.getText());
        ser.setData(txtDataEHora.getText());
        ser.setComplemento(textoComplemento.getText());
        ser.setOs(Integer.parseInt(txtOs.getText()));

        serDao.Salvar(ser);

    }

    public void SalvarItens() {
        CadastroDeServico ser = new CadastroDeServico();

        int cont = tbOrdemDeServico.getRowCount();

        ser.setContador(cont); // Crio um Contador para receber o valor da Tabela para validar no DAO

        for (int x = 0; x < cont; x++) {

            CadastroDeServico ser1 = new CadastroDeServico();
            ser1.setOs(Integer.parseInt(txtOs.getText()));
            ser1.setDescricao(tableModel.getValueAt(x, 0).toString());
            ser1.setValorTotal(Double.parseDouble(tableModel.getValueAt(x, 1).toString()));
            ser1.setQuantidade(Integer.parseInt(tableModel.getValueAt(x, 2).toString()));

            OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();
            serDao.SalvarItens(ser1);
            serDao.AlterarEstoque(ser1);
        }

        JOptionPane.showMessageDialog(null, "Itens da Nota SALVO com sucesso!", "Mensagem",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void GerarPDF() {
        CadastroDeServico ser = new CadastroDeServico();

        ser.setOs(Integer.parseInt(txtOs.getText()));
        ser.setCliente(txtPesquisaCliente.getText());
        ser.setComplemento(textoComplemento.getText());
        ser.setData(txtDataEHora.getText());
        ser.setDataAgendamento(jDataDoAgendamento.getText());
        ser.setHorarioAgendamento(jHorarioAgendamento.getText());
        ser.setValorTotal(Double.parseDouble(textoValor.getText()));
        ser.setDesconto(Double.parseDouble(txtDesconto.getText().replace(",", ".")));

        CadastroDeClientes cli = new CadastroDeClientes();

        GeradorDePdf geraPdf = new GeradorDePdf();
        geraPdf.GeraPDFOrdemDeServico(ser, cli);

    }

    private void BuscarOS() {
        CadastroDeServico ser = new CadastroDeServico();

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();

        serDao.BuscarOS(ser);

        txtOs.setText(Integer.toString(ser.getOs()));

    }


    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        Buscar();

    }//GEN-LAST:event_btnEditarActionPerformed

    private void Buscar() {
        CadastroDeServico ser = new CadastroDeServico();

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();

        ser.setOs(Integer.parseInt(txtOs.getText()));

        serDao.Buscar(ser);
        serDao.BuscarItensDoServico(ser);

        txtPesquisaCliente.setText(ser.getCliente());
        txtDesconto.setText(Double.toString(ser.getDesconto()));
        jDataDoAgendamento.setText(ser.getDataAgendamento());
        textoValor.setText(Double.toString(ser.getValorTotal()));
        textoComplemento.setText(ser.getComplemento());
        jHorarioAgendamento.setText(ser.getHorarioAgendamento());

        List<CadastroDeServico> lista = serDao.BuscarItensDoServico(ser);
        for (int x = 0; x < lista.size(); x++) {

            CadastroDeServico ser1 = new CadastroDeServico();

            ser1.setDescricao(lista.get(x).getDescricao());
            ser1.setQuantidade(lista.get(x).getQuantidade());
            ser1.setValorTotal(lista.get(x).getValorTotal());

            tableModel.addRow(ser1);
        }
        ContadorDaTabela(); //Chama o metodo de Somar o Valor total e a quantidade de linhas na tabela
    }

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed

        AlterarNota();

        JOptionPane.showMessageDialog(null, "Nota ALTERADA com sucesso!", "Mensagem",
                JOptionPane.INFORMATION_MESSAGE);

        GerarPDF();
        Limpar();

    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void AlterarNota() {
        CadastroDeServico ser = new CadastroDeServico();

        ser.setCliente(txtPesquisaCliente.getText());
        ser.setOs(Integer.parseInt(txtOs.getText()));
        ser.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        ser.setComplemento(textoComplemento.getText());
        ser.setDesconto(Double.parseDouble(txtDesconto.getText().replace(",", ".")));
        ser.setValorTotal(Double.parseDouble(textoValor.getText().replace(",", ".")));
        ser.setDataAgendamento(jDataDoAgendamento.getText());
        ser.setHorarioAgendamento(jHorarioAgendamento.getText());

        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();
        serDao.VerificaCodigoNoBanco(ser);
        serDao.VerificaCodigoDeItensNoBanco(ser);

        if (ser.isValidadorNota()) {   //ALTERA A NOTA SE TIVER

            serDao.AlterarNota(ser);

        }

        if (ser.isValidadorItens()) { // ALTERAR OS ITENS SE TIVER

            int cont = tbOrdemDeServico.getRowCount();

            ser.setContador(cont); // Crio um Contador para receber o valor da Tabela para validar no DAO
            System.out.println(ser.getContador());

            serDao.DeletaItens(ser); // DELETA TODOS OS ITENS DA TABELA 
            for (int x = 0; x < cont; x++) {

                CadastroDeServico ser1 = new CadastroDeServico();
                ser1.setOs(Integer.parseInt(txtOs.getText()));
                ser1.setDescricao(tableModel.getValueAt(x, 0).toString());
                ser1.setValorTotal(Double.parseDouble(tableModel.getValueAt(x, 1).toString()));
                ser1.setQuantidade(Integer.parseInt(tableModel.getValueAt(x, 2).toString()));

                serDao.SalvarItens(ser1); // CRIA TODOS OS NOVOS ITENS DA TABELA
                //   serDao.AlterarEstoque(ser1);
            }

        }

    }

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        Limpar();
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int contadorTabelaConsulta = tabelaConsulta.getRowCount();

        for (int x = 0; x < contadorTabelaConsulta; x++) {
            tabelaConsultaOrdem.removeRow(0);
        }

        BuscarNotasDeServicos();

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tabelaConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMousePressed
        // CLIQUE NA TABELA DE CONSULTA CLIENTES

        int lin = tabelaConsulta.getSelectedRow();

        String os = tabelaConsulta.getModel().getValueAt(lin, 0).toString();
        String descricao = tabelaConsulta.getModel().getValueAt(lin, 1).toString();
        String status = tabelaConsulta.getModel().getValueAt(lin, 4).toString();

        txtOsConsulta.setText(os);
        txtClienteConsulta.setText(descricao);
        comboBoxStatusConsulta.setSelectedItem(status);

    }//GEN-LAST:event_tabelaConsultaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SalvarStatus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMousePressed

    private void cmdAbertoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAbertoMousePressed

        cmdFechado.setSelected(false);
        cmdTodos.setSelected(false);
        cmdOs.setSelected(false);
        txtOsConsultaInformar.setEnabled(false);
        cmdCliente.setSelected(false);
        txtPesquisaClienteConsulta.setEnabled(false);
        cmdCancelado.setSelected(false);

    }//GEN-LAST:event_cmdAbertoMousePressed

    private void cmdFechadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdFechadoMousePressed

        cmdAberto.setSelected(false);
        cmdTodos.setSelected(false);
        cmdOs.setSelected(false);
        txtOsConsultaInformar.setEnabled(false);
        cmdCliente.setSelected(false);
        txtPesquisaClienteConsulta.setEnabled(false);
        cmdCancelado.setSelected(false);

    }//GEN-LAST:event_cmdFechadoMousePressed

    private void cmdTodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdTodosMousePressed

        cmdAberto.setSelected(false);
        cmdFechado.setSelected(false);
        cmdOs.setSelected(false);
        txtOsConsultaInformar.setEnabled(false);
        cmdCliente.setSelected(false);
        txtPesquisaClienteConsulta.setEnabled(false);
        cmdCancelado.setSelected(false);

    }//GEN-LAST:event_cmdTodosMousePressed

    private void cmdOsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdOsMousePressed

        if (cmdOs.isSelected()) {

            txtOsConsultaInformar.setEnabled(false);

        } else {

            txtOsConsultaInformar.setEnabled(true);
        }

        cmdAberto.setSelected(false);
        cmdFechado.setSelected(false);
        cmdCliente.setSelected(false);
        cmdTodos.setSelected(false);
        txtPesquisaClienteConsulta.setEnabled(false);
        cmdCancelado.setSelected(false);

    }//GEN-LAST:event_cmdOsMousePressed

    private void cmdClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdClienteMousePressed

        if (cmdCliente.isSelected()) {

            txtPesquisaClienteConsulta.setEnabled(false);

        } else {

            txtPesquisaClienteConsulta.setEnabled(true);

        }

        cmdOs.setSelected(false);
        txtOsConsultaInformar.setEnabled(false);
        cmdAberto.setSelected(false);
        cmdFechado.setSelected(false);
        cmdTodos.setSelected(false);
        cmdCancelado.setSelected(false);

    }//GEN-LAST:event_cmdClienteMousePressed

    private void cmdOsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdOsMouseClicked

    }//GEN-LAST:event_cmdOsMouseClicked

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        GerarPdfBuscaNotas();
    }//GEN-LAST:event_btnPdfActionPerformed

    private void txtPesquisaClienteConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaClienteConsultaActionPerformed
        listaConsultaCliente.setVisible(false);
        Enter1 = 1;
    }//GEN-LAST:event_txtPesquisaClienteConsultaActionPerformed

    private void txtPesquisaClienteConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaClienteConsultaKeyReleased
        if (Enter1 == 0) {
            ListaDePesquisaConsulta();
        } else {
            Enter1 = 0;
        }
    }//GEN-LAST:event_txtPesquisaClienteConsultaKeyReleased

    private void listaConsultaClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaConsultaClienteMousePressed
        MostrarPesquisaConsulta();
        listaConsultaCliente.setVisible(false);
    }//GEN-LAST:event_listaConsultaClienteMousePressed

    private void jHorarioAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHorarioAgendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHorarioAgendamentoActionPerformed

    private void txtPesquisaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaClienteKeyReleased
        if (Enter == 0) {
            ListaDePesquisa();
        } else {
            Enter = 0;
        }
    }//GEN-LAST:event_txtPesquisaClienteKeyReleased

    private void txtPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaClienteActionPerformed
        Lista.setVisible(false);
        Enter = 1;
    }//GEN-LAST:event_txtPesquisaClienteActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String valor = "";

        valor.valueOf(InsereValorNaTabela());
        if (tbOrdemDeServico.getSelectedRow() != -1) { // Se for diferente de -1 existe algo na tabela.
            tableModel.setValueAt(comboBoxProduto.getSelectedItem().toString(), tbOrdemDeServico.getSelectedRow(), 0);
            tableModel.setValueAt(valor.valueOf(InsereValorNaTabela()), tbOrdemDeServico.getSelectedRow(), 1);
            tableModel.setValueAt(txtQuantidade.getText(), tbOrdemDeServico.getSelectedRow(), 2);
            ContadorDaTabela(); //Chama o metodo de Somar o Valor total e a quantidade de linhas na tabela
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (tbOrdemDeServico.getSelectedRow() != -1) {

            tableModel.removeRow(tbOrdemDeServico.getSelectedRow());
            ContadorDaTabela(); //Chama o metodo de Somar o Valor total e a quantidade de linhas na tabela

        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        InserirNaTabela();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseClicked
        txtQuantidade.setText("1");
    }//GEN-LAST:event_btnAdicionarMouseClicked

    private void ListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMousePressed
        MostrarPesquisa();
        Lista.setVisible(false);
    }//GEN-LAST:event_ListaMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GerarPDF();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdCanceladoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdCanceladoMousePressed
        cmdAberto.setSelected(false);
        cmdFechado.setSelected(false);
        cmdCliente.setSelected(false);
        cmdTodos.setSelected(false);
    }//GEN-LAST:event_cmdCanceladoMousePressed

    private void GerarPdfBuscaNotas() {

        CadastroDeServico ser = new CadastroDeServico();
        ser.setCliente(txtPesquisaClienteConsulta.getText());

        if (cmdOs.isSelected()) {

            ser.setOs(Integer.parseInt(txtOsConsultaInformar.getText()));
            ser.setClicked("OS");

        } else if (cmdCliente.isSelected()) {

            ser.setClicked("CLIENTE");

        } else if (cmdAberto.isSelected()) {

            ser.setStatus("ABERTO");
            ser.setClicked("ABERTO");

        } else if (cmdFechado.isSelected()) {

            ser.setStatus("FECHADO");
            ser.setClicked("FECHADO");

        }else if (cmdCancelado.isSelected()) {

            ser.setStatus("CANCELADO");
            ser.setClicked("CANCELADO");

        } else if (cmdTodos.isSelected()) {

            ser.setClicked("TODOS");

        }else {
            JOptionPane.showMessageDialog(null, "SELECIONE UMA DAS OPÇÕES DE AÇÕES", "Mensagem",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        GeradorDePdf pdf = new GeradorDePdf();

        pdf.GerarPDFBuscaDeNotas(ser);

    }

    private void SalvarStatus() {
        CadastroDeServico ser = new CadastroDeServico();

        ser.setCliente(txtClienteConsulta.getText());
        ser.setOs(Integer.parseInt(txtOsConsulta.getText()));
        ser.setStatus((String) comboBoxStatusConsulta.getSelectedItem());

        int resposta = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA MUDAR O STATUS DESSA NOTA PARA '" + comboBoxStatusConsulta.getSelectedItem() + "'", "escolha dois", JOptionPane.YES_NO_OPTION);
        //verfica se a resposta é verdadeira
        if (resposta == JOptionPane.YES_OPTION) {
            OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();
            serDao.SalvarStatusDaNota(ser);

            txtOsConsulta.setText("");
            txtClienteConsulta.setText("");
            int contadorTabelaConsulta = tabelaConsulta.getRowCount();

            for (int x = 0; x < contadorTabelaConsulta; x++) {
                tabelaConsultaOrdem.removeRow(0);
            }
            BuscarNotasDeServicos();
        }

    }

    public void BuscarNotasDeServicos() {

        CadastroDeServico ser = new CadastroDeServico();
        OrdemDeServicoDAO serDao = new OrdemDeServicoDAO();

        ser.setCliente(txtPesquisaClienteConsulta.getText());

        if (cmdOs.isSelected()) {

            ser.setOs(Integer.parseInt(txtOsConsultaInformar.getText()));
            ser.setClicked("OS");

        } else if (cmdCliente.isSelected()) {

            ser.setClicked("CLIENTE");

        } else if (cmdAberto.isSelected()) {

            ser.setStatus("ABERTO");
            ser.setClicked("ABERTO");

        } else if (cmdFechado.isSelected()) {

            ser.setStatus("FECHADO");
            ser.setClicked("FECHADO");

        } else if (cmdCancelado.isSelected()) {
            
            ser.setStatus("CANCELADO");
            ser.setClicked("CANCELADO");

        } else if (cmdTodos.isSelected()) {

            ser.setClicked("TODOS");

        } else {
            JOptionPane.showMessageDialog(null, "SELECIONE UMA DAS OPÇÕES DE AÇÕES", "Mensagem",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        List<CadastroDeServico> lista = serDao.BuscarNotasDeServico(ser);

        if (lista.size() == 0) {
            JOptionPane.showMessageDialog(null, "NÃO FORAM ENCONTRADOS DADOS PARA PARÂMETROS INFORMADOS!", "Mensagem",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (int x = 0; x < lista.size(); x++) {
                CadastroDeServico ser1 = new CadastroDeServico();

                ser1.setOs(lista.get(x).getOs());
                ser1.setCliente(lista.get(x).getCliente());
                ser1.setDataAgendamento(lista.get(x).getDataAgendamento());
                ser1.setData(lista.get(x).getData());
                ser1.setStatus(lista.get(x).getStatus());

                tabelaConsultaOrdem.addRow(ser1);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOrdemDeServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JLabel clien;
    private javax.swing.JCheckBox cmdAberto;
    private javax.swing.JCheckBox cmdCancelado;
    private javax.swing.JCheckBox cmdCliente;
    private javax.swing.JCheckBox cmdFechado;
    private javax.swing.JCheckBox cmdOs;
    private javax.swing.JCheckBox cmdTodos;
    private javax.swing.JComboBox<String> comboBoxProduto;
    private javax.swing.JComboBox<String> comboBoxStatusConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jDataDoAgendamento;
    private javax.swing.JFormattedTextField jHorarioAgendamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jtConsultaOrdens;
    private javax.swing.JList<String> listaConsultaCliente;
    private javax.swing.JTable tabelaConsulta;
    private javax.swing.JTable tbOrdemDeServico;
    private javax.swing.JTextPane textoComplemento;
    private javax.swing.JLabel textoQuantidadeDeItens;
    private javax.swing.JLabel textoValor;
    private javax.swing.JTextField txtClienteConsulta;
    private javax.swing.JLabel txtDataEHora;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtOs;
    private javax.swing.JTextField txtOsConsulta;
    private javax.swing.JTextField txtOsConsultaInformar;
    private javax.swing.JTextField txtPesquisaCliente;
    private javax.swing.JTextField txtPesquisaClienteConsulta;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

}
